"""Build the Undying menu assets from Barlow Semi Condensed (SIL OFL 1.1).

Outputs (into OUT):
  guis/textures/ppu/font_r.png, font_s.png, font_b.png  glyph atlases (white + alpha), one per weight
  guis/textures/ppu/shapes.png                          corners, rings, circles, fades, shadow, lock
  ppu_assets.lua                                         metrics, kerning, atlas rects (layout px)

All glyphs are rendered at SCALE x the layout size, so they stay sharp when the game
stretches its 1280x720 layout to 1080p-1440p.
"""
import os, sys, math
from PIL import Image, ImageDraw, ImageFont, ImageFilter
import uharfbuzz as hb

SCALE = 2
FONTDIR = sys.argv[1]
OUT = sys.argv[2]
FALLBACK = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FALLBACK_B = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
# Arrows the browser takes from a fallback font: ↑↓ look like Arial's (Liberation Sans is metric-compatible)
ARROW_FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
ARROW_FONT_B = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

WEIGHTS = {
    "r": ("BarlowSemiCondensed-Regular.ttf", FALLBACK, [11, 12, 13, 14, 15, 16, 18]),
    "s": ("BarlowSemiCondensed-SemiBold.ttf", FALLBACK_B, [11, 12, 13, 14, 15, 16]),
    "b": ("BarlowSemiCondensed-Bold.ttf", FALLBACK_B, [11, 12, 13, 14, 16, 23]),
}
CHARS = [chr(c) for c in range(32, 127)] + list("‹›◂▸▾↑↓·…×—–’‘“”€£°•")

def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def pack(items, width):
    """Shelf packer. items: list of (key, w, h). Returns {key: (x, y)}, height."""
    x = y = shelf = 0
    pos = {}
    for key, w, h in sorted(items, key=lambda t: -t[2]):
        if x + w > width:
            x = 0
            y += shelf + 1
            shelf = 0
        pos[key] = (x, y)
        x += w + 1
        shelf = max(shelf, h)
    return pos, y + shelf

def pow2(n):
    p = 1
    while p < n:
        p *= 2
    return p

lua = ["-- Generated by gen_assets.py from Barlow Semi Condensed (SIL Open Font License 1.1). Do not edit.",
       "-- Glyph metrics are in layout pixels; atlas rects are in texture pixels (SCALE x).",
       "PPU_ASSETS = { scale = %d, fonts = {}, kern = {}, shapes = {} }" % SCALE,
       "local F, K, S = PPU_ASSETS.fonts, PPU_ASSETS.kern, PPU_ASSETS.shapes"]

os.makedirs(os.path.join(OUT, "guis/textures/ppu"), exist_ok=True)

for wkey, (fname, fbname, sizes) in WEIGHTS.items():
    path = os.path.join(FONTDIR, fname)
    from fontTools.ttLib import TTFont
    tt = TTFont(path)
    cmap = tt.getBestCmap()
    upem = tt["head"].unitsPerEm
    asc = tt["hhea"].ascent / upem
    desc = -tt["hhea"].descent / upem
    gap = tt["hhea"].lineGap / upem

    glyphs = {}  # (size, ch) -> dict
    items = []
    for size in sizes:
        px = size * SCALE
        main = ImageFont.truetype(path, px)
        fb = ImageFont.truetype(fbname, px)
        arrow = ImageFont.truetype(ARROW_FONT if wkey == "r" else ARROW_FONT_B, px)
        for ch in CHARS:
            f = main if ord(ch) in cmap else (arrow if ch in "↑↓" else fb)
            adv = f.getlength(ch) / SCALE
            bbox = f.getbbox(ch, anchor="ls")  # relative to left/baseline
            if bbox[2] - bbox[0] <= 0 or ch == " ":
                glyphs[(size, ch)] = dict(adv=adv, w=0, h=0, xo=0, yo=0)
                continue
            pad = 1
            w = bbox[2] - bbox[0] + pad * 2
            h = bbox[3] - bbox[1] + pad * 2
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((pad - bbox[0], pad - bbox[1]), ch, font=f, fill=255, anchor="ls")
            key = (size, ch)
            glyphs[key] = dict(adv=adv, w=w, h=h, xo=(bbox[0] - pad) / SCALE, yo=(bbox[1] - pad) / SCALE, img=img)
            items.append((key, w, h))

    AW = 1024
    pos, used_h = pack(items, AW)
    AH = pow2(used_h + 1)
    atlas = Image.new("RGBA", (AW, AH), (255, 255, 255, 0))
    for key, (x, y) in pos.items():
        g = glyphs[key]
        white = Image.new("RGBA", g["img"].size, (255, 255, 255, 255))
        white.putalpha(g["img"])
        atlas.paste(white, (x, y))
        g["x"], g["y"] = x, y
    atlas.save(os.path.join(OUT, "guis/textures/ppu/font_%s.png" % wkey))
    print("font_%s.png %dx%d, %d glyphs" % (wkey, AW, AH, len(items)))

    for size in sizes:
        lua.append("F.%s%d = { tex = \"guis/textures/ppu/font_%s\", size = %d, asc = %.4f, desc = %.4f, gap = %.4f, g = {" % (wkey, size, wkey, size, asc * size, desc * size, gap * size))
        parts = []
        for ch in CHARS:
            g = glyphs[(size, ch)]
            if g["w"]:
                parts.append("[%s]={%.3f,%.3f,%.3f,%d,%d,%d,%d}" % (lua_str(ch), g["adv"], g["xo"], g["yo"], g["x"], g["y"], g["w"], g["h"]))
            else:
                parts.append("[%s]={%.3f}" % (lua_str(ch), g["adv"]))
        lua.append("  " + ",".join(parts) + " }}")

    # Kerning (font units / upem -> multiply by size in Lua), from HarfBuzz shaping of each pair
    blob = hb.Blob.from_file_path(path)
    face = hb.Face(blob)
    font = hb.Font(face)
    font.scale = (upem, upem)
    def advs(text):
        buf = hb.Buffer()
        buf.add_str(text)
        buf.guess_segment_properties()
        hb.shape(font, buf, {"kern": True, "liga": False})
        return [p.x_advance for p in buf.glyph_positions]
    single = {}
    ascii_chars = [c for c in CHARS if ord(c) in cmap]
    for c in ascii_chars:
        single[c] = advs(c)[0]
    kern = []
    for a in ascii_chars:
        for b in ascii_chars:
            pa = advs(a + b)
            if len(pa) == 2:
                d = pa[0] - single[a]
                if d != 0:
                    kern.append("[%s]=%.4f" % (lua_str(a + b), d / upem))
    lua.append("K.%s = {%s}" % (wkey, ",".join(kern)))
    print("kern %s: %d pairs" % (wkey, len(kern)))

# ---------------- shapes ----------------
shapes = []  # (name, Image, layout_w, layout_h)
def aa_draw(w, h, fn, ss=4):
    big = Image.new("L", (w * ss, h * ss), 0)
    fn(ImageDraw.Draw(big), ss)
    return big.resize((w, h), Image.LANCZOS)

def white(mask):
    im = Image.new("RGBA", mask.size, (255, 255, 255, 255))
    im.putalpha(mask)
    return im

def quads(im):
    return [("tl", im), ("tr", im.transpose(Image.FLIP_LEFT_RIGHT)),
            ("bl", im.transpose(Image.FLIP_TOP_BOTTOM)), ("br", im.transpose(Image.ROTATE_180))]

for r in (2, 3, 4, 10, 12):
    R = r * SCALE
    # filled quarter (top-left), center of circle at (R, R)
    m = aa_draw(R, R, lambda d, ss, R=R: d.ellipse([0, 0, 2 * R * ss - 1, 2 * R * ss - 1], fill=255))
    for tag, im in quads(white(m)):
        shapes.append(("corner%d_%s" % (r, tag), im, r, r))
    # 1px ring quarter (top-left)
    def ring(d, ss, R=R):
        d.ellipse([0, 0, 2 * R * ss - 1, 2 * R * ss - 1], fill=255)
        t = SCALE * ss
        d.ellipse([t, t, 2 * R * ss - 1 - t, 2 * R * ss - 1 - t], fill=0)
    m = aa_draw(R, R, ring)
    for tag, im in quads(white(m)):
        shapes.append(("ring%d_%s" % (r, tag), im, r, r))

for d_ in (14, 16):
    D = d_ * SCALE
    m = aa_draw(D, D, lambda d, ss, D=D: d.ellipse([0, 0, D * ss - 1, D * ss - 1], fill=255))
    shapes.append(("circle%d" % d_, white(m), d_, d_))

# Tab-arrow fades: solid until 55%, then linear to 0 (CSS linear-gradient(90deg, bg 55%, transparent))
FW = 34 * SCALE
fade = Image.new("L", (FW, 4), 0)
for x in range(FW):
    t = (x + 0.5) / FW
    a = 1.0 if t <= 0.55 else max(0.0, 1 - (t - 0.55) / 0.45)
    for y in range(4):
        fade.putpixel((x, y), int(round(a * 255)))
shapes.append(("fade_l", white(fade), 34, 2))  # opaque on the left
shapes.append(("fade_r", white(fade.transpose(Image.FLIP_LEFT_RIGHT)), 34, 2))

# Window shadow (box-shadow: 0 14px 44px rgba(0,0,0,.5)): 9-slice of a blurred box. Layout px, SCALE 1 is enough.
M = 48  # margin around the box where the blur fades out
BOX = 192
sh = Image.new("L", (BOX + 2 * M, BOX + 2 * M), 0)
ImageDraw.Draw(sh).rectangle([M, M, M + BOX - 1, M + BOX - 1], fill=255)
sh = sh.filter(ImageFilter.GaussianBlur(22))
shapes.append(("shadow", white(sh), BOX + 2 * M, BOX + 2 * M))

# Lock icon (design svg: rect x2 y5.5 w8 h6 rx1 + shackle path), 12x12
def lock(d, ss):
    k = SCALE * ss
    d.rounded_rectangle([2 * k, 5.5 * k, 10 * k, 11.5 * k], radius=1 * k, fill=255)
    d.arc([4 * k, 2 * k, 8 * k, 6 * k], 180, 360, fill=255, width=int(1.4 * k))
    d.line([4 * k + 0.7 * k, 4 * k, 4 * k + 0.7 * k, 5.5 * k], fill=255, width=int(1.4 * k))
    d.line([8 * k - 0.7 * k, 4 * k, 8 * k - 0.7 * k, 5.5 * k], fill=255, width=int(1.4 * k))
shapes.append(("lock", white(aa_draw(12 * SCALE, 12 * SCALE, lock)), 12, 12))

# plain white pixel block (for tinted solid rects when needed)
shapes.append(("white", Image.new("RGBA", (4, 4), (255, 255, 255, 255)), 4, 4))

items = [(n, im.size[0], im.size[1]) for n, im, _, _ in shapes]
pos, used_h = pack(items, 512)  # shapes
AH = pow2(used_h + 1)
atlas = Image.new("RGBA", (512, AH), (255, 255, 255, 0))
for n, im, lw, lh in shapes:
    x, y = pos[n]
    atlas.paste(im, (x, y))
    tex_scale = 1 if n == "shadow" else SCALE
    lua.append("S.%s = { %d, %d, %d, %d, %d, %d }" % (n, x, y, im.size[0], im.size[1], lw, lh))
atlas.save(os.path.join(OUT, "guis/textures/ppu/shapes.png"))
lua.append("PPU_ASSETS.shape_tex = \"guis/textures/ppu/shapes\"")
lua.append("PPU_ASSETS.shadow_margin = %d" % M)
lua.append("PPU_ASSETS.shadow_slice = %d" % (M + 48))
print("shapes.png 512x%d" % AH)

with open(os.path.join(OUT, "ppu_assets.lua"), "w", newline="\n") as f:
    f.write("\n".join(lua) + "\n")
print("lua bytes", os.path.getsize(os.path.join(OUT, "ppu_assets.lua")))
