"""Build the Undying menu assets from Barlow Semi Condensed (SIL OFL 1.1).

Outputs (into OUT):
  guis/textures/ppu/font_r.png, font_s.png, font_b.png  glyph atlases, 2x (used when UI scale > 1.25)
  guis/textures/ppu/font_r_1x.png, ...                  glyph atlases, 1x (UI scale up to 1.25)
  guis/textures/ppu/shapes.png, shapes_1x.png           corners, rings, circles, fades, shadow, lock
  ppu_assets.lua                                         metrics, kerning, atlas rects

Usage: python3 gen_menu_assets.py <folder with BarlowSemiCondensed-*.ttf> <output folder>
Needs: Pillow, fontTools, uharfbuzz, and DejaVu Sans + Liberation Sans installed (fallback glyphs).
Advances come from the font's own units (unhinted, like the browser), so the layout is the
same for both sets; only the pixels differ.
"""
import os, sys
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from fontTools.ttLib import TTFont
import uharfbuzz as hb

FONTDIR = sys.argv[1]
OUT = sys.argv[2]
FALLBACK = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FALLBACK_B = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
# Arrows the browser takes from a fallback font: up/down look like Arial's (Liberation Sans is metric-compatible)
ARROW_FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"
ARROW_FONT_B = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

WEIGHTS = {
    "r": ("BarlowSemiCondensed-Regular.ttf", FALLBACK, ARROW_FONT, [11, 12, 13, 14, 15, 16, 18]),
    "s": ("BarlowSemiCondensed-SemiBold.ttf", FALLBACK_B, ARROW_FONT_B, [11, 12, 13, 14, 15, 16]),
    "b": ("BarlowSemiCondensed-Bold.ttf", FALLBACK_B, ARROW_FONT_B, [11, 12, 13, 14, 16, 23]),
}
CHARS = [chr(c) for c in range(32, 127)] + list("‹›◂▸▾↑↓·…×—–’‘“”€£°•")
SETS = [(2, ""), (1, "_1x")]


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def pack(items, width):
    """Shelf packer. items: list of (key, w, h). Returns {key: (x, y)}, height."""
    x = y = shelf = 0
    pos = {}
    for key, w, h in sorted(items, key=lambda t: -t[2]):
        if x + w > width:
            x = 0
            y += shelf + 1
            shelf = 0
        pos[key] = (x, y)
        x += w + 1
        shelf = max(shelf, h)
    return pos, y + shelf


def pow2(n):
    p = 1
    while p < n:
        p *= 2
    return p


def white(mask):
    im = Image.new("RGBA", mask.size, (255, 255, 255, 255))
    im.putalpha(mask)
    return im


def unit_advance(path):
    """advance(ch) in em units, from the font itself (no hinting)."""
    tt = TTFont(path)
    cmap = tt.getBestCmap()
    upem = tt["head"].unitsPerEm
    hmtx = tt["hmtx"]
    def adv(ch):
        g = cmap.get(ord(ch))
        return None if g is None else hmtx[g][0] / upem
    return adv, cmap


lua = ["-- Generated by gen_menu_assets.py from Barlow Semi Condensed (SIL Open Font License 1.1). Do not edit.",
       "-- Glyph metrics are in UI pixels; atlas rects are in texture pixels (the set's scale x).",
       "PPU_ASSETS = { kern = {}, sets = {} }",
       "local K = PPU_ASSETS.kern",
       "local F, S"]

os.makedirs(os.path.join(OUT, "guis/textures/ppu"), exist_ok=True)

# ---------------- kerning (shared by both sets) ----------------
for wkey, (fname, _, _, _) in WEIGHTS.items():
    path = os.path.join(FONTDIR, fname)
    tt = TTFont(path)
    cmap = tt.getBestCmap()
    upem = tt["head"].unitsPerEm
    font = hb.Font(hb.Face(hb.Blob.from_file_path(path)))
    font.scale = (upem, upem)
    def advs(text):
        buf = hb.Buffer()
        buf.add_str(text)
        buf.guess_segment_properties()
        hb.shape(font, buf, {"kern": True, "liga": False})
        return [p.x_advance for p in buf.glyph_positions]
    chars = [c for c in CHARS if ord(c) in cmap]
    single = {c: advs(c)[0] for c in chars}
    kern = []
    for a in chars:
        for b in chars:
            pa = advs(a + b)
            if len(pa) == 2 and pa[0] != single[a]:
                kern.append("[%s]=%.4f" % (lua_str(a + b), (pa[0] - single[a]) / upem))
    lua.append("K.%s = {%s}" % (wkey, ",".join(kern)))
    print("kern %s: %d pairs" % (wkey, len(kern)))


def build_set(SCALE, suffix):
    lua.append("F, S = {}, {}")
    lua.append("PPU_ASSETS.sets[%d] = { scale = %d, fonts = F, shapes = S, shape_tex = \"guis/textures/ppu/shapes%s\" }" % (SCALE, SCALE, suffix))
    for wkey, (fname, fbname, arrowname, sizes) in WEIGHTS.items():
        path = os.path.join(FONTDIR, fname)
        adv_main, cmap = unit_advance(path)
        adv_fb, _ = unit_advance(fbname)
        adv_arrow, _ = unit_advance(arrowname)
        tt = TTFont(path)
        upem = tt["head"].unitsPerEm
        asc = tt["OS/2"].sTypoAscender / upem   # USE_TYPO_METRICS is set in Barlow
        desc = -tt["OS/2"].sTypoDescender / upem
        gap = tt["OS/2"].sTypoLineGap / upem

        glyphs = {}
        items = []
        for size in sizes:
            px = size * SCALE
            main = ImageFont.truetype(path, px)
            fb = ImageFont.truetype(fbname, px)
            arrow = ImageFont.truetype(arrowname, px)
            for ch in CHARS:
                if ord(ch) in cmap:
                    f, adv = main, adv_main(ch)
                elif ch in "↑↓":
                    f, adv = arrow, adv_arrow(ch)
                else:
                    f, adv = fb, adv_fb(ch)
                adv = (adv or 0.5) * size
                bbox = f.getbbox(ch, anchor="ls")
                if bbox[2] - bbox[0] <= 0 or ch == " ":
                    glyphs[(size, ch)] = dict(adv=adv, w=0)
                    continue
                pad = 1
                w = bbox[2] - bbox[0] + pad * 2
                h = bbox[3] - bbox[1] + pad * 2
                img = Image.new("L", (w, h), 0)
                ImageDraw.Draw(img).text((pad - bbox[0], pad - bbox[1]), ch, font=f, fill=255, anchor="ls")
                glyphs[(size, ch)] = dict(adv=adv, w=w, h=h, xo=(bbox[0] - pad) / SCALE, yo=(bbox[1] - pad) / SCALE, img=img)
                items.append(((size, ch), w, h))

        AW = 1024 if SCALE > 1 else 512
        pos, used_h = pack(items, AW)
        AH = pow2(used_h + 1)
        atlas = Image.new("RGBA", (AW, AH), (255, 255, 255, 0))
        for key, (x, y) in pos.items():
            g = glyphs[key]
            atlas.paste(white(g["img"]), (x, y))
            g["x"], g["y"] = x, y
        tex = "guis/textures/ppu/font_%s%s" % (wkey, suffix)
        atlas.save(os.path.join(OUT, tex + ".png"))
        print("%s.png %dx%d" % (tex, AW, AH))

        for size in sizes:
            lua.append("F.%s%d = { tex = \"%s\", size = %d, asc = %.4f, desc = %.4f, gap = %.4f, g = {" % (wkey, size, tex, size, asc * size, desc * size, gap * size))
            parts = []
            for ch in CHARS:
                g = glyphs[(size, ch)]
                if g["w"]:
                    parts.append("[%s]={%.3f,%.3f,%.3f,%d,%d,%d,%d}" % (lua_str(ch), g["adv"], g["xo"], g["yo"], g["x"], g["y"], g["w"], g["h"]))
                else:
                    parts.append("[%s]={%.3f}" % (lua_str(ch), g["adv"]))
            lua.append("  " + ",".join(parts) + " }}")

    # ---------------- shapes ----------------
    shapes = []
    def aa_draw(w, h, fn, ss=8):
        big = Image.new("L", (w * ss, h * ss), 0)
        fn(ImageDraw.Draw(big), ss)
        return big.resize((w, h), Image.LANCZOS)

    def quads(im):
        return [("tl", im), ("tr", im.transpose(Image.FLIP_LEFT_RIGHT)),
                ("bl", im.transpose(Image.FLIP_TOP_BOTTOM)), ("br", im.transpose(Image.ROTATE_180))]

    for r in (2, 3, 4, 10, 12):
        R = r * SCALE
        m = aa_draw(R, R, lambda d, ss, R=R: d.ellipse([0, 0, 2 * R * ss - 1, 2 * R * ss - 1], fill=255))
        for tag, im in quads(white(m)):
            shapes.append(("corner%d_%s" % (r, tag), im, r, r))
        def ring(d, ss, R=R):
            d.ellipse([0, 0, 2 * R * ss - 1, 2 * R * ss - 1], fill=255)
            t = SCALE * ss
            d.ellipse([t, t, 2 * R * ss - 1 - t, 2 * R * ss - 1 - t], fill=0)
        m = aa_draw(R, R, ring)
        for tag, im in quads(white(m)):
            shapes.append(("ring%d_%s" % (r, tag), im, r, r))

    for d_ in (14, 16, 18, 20):
        Dp = d_ * SCALE
        m = aa_draw(Dp, Dp, lambda d, ss, Dp=Dp: d.ellipse([0, 0, Dp * ss - 1, Dp * ss - 1], fill=255))
        shapes.append(("circle%d" % d_, white(m), d_, d_))

    FW = 34 * SCALE
    fade = Image.new("L", (FW, 4), 0)
    for x in range(FW):
        t = (x + 0.5) / FW
        a = 1.0 if t <= 0.55 else max(0.0, 1 - (t - 0.55) / 0.45)
        for y in range(4):
            fade.putpixel((x, y), int(round(a * 255)))
    shapes.append(("fade_l", white(fade), 34, 2))
    shapes.append(("fade_r", white(fade.transpose(Image.FLIP_LEFT_RIGHT)), 34, 2))

    M, BOX = 48, 192
    sh = Image.new("L", (BOX + 2 * M, BOX + 2 * M), 0)
    ImageDraw.Draw(sh).rectangle([M, M, M + BOX - 1, M + BOX - 1], fill=255)
    sh = sh.filter(ImageFilter.GaussianBlur(22))
    shapes.append(("shadow", white(sh), BOX + 2 * M, BOX + 2 * M))

    def lock(d, ss):
        k = SCALE * ss
        d.rounded_rectangle([2 * k, 5.5 * k, 10 * k, 11.5 * k], radius=1 * k, fill=255)
        d.arc([4 * k, 2 * k, 8 * k, 6 * k], 180, 360, fill=255, width=int(1.4 * k))
        d.line([4.7 * k, 4 * k, 4.7 * k, 5.5 * k], fill=255, width=int(1.4 * k))
        d.line([7.3 * k, 4 * k, 7.3 * k, 5.5 * k], fill=255, width=int(1.4 * k))
    shapes.append(("lock", white(aa_draw(12 * SCALE, 12 * SCALE, lock)), 12, 12))

    items = [(n, im.size[0], im.size[1]) for n, im, _, _ in shapes]
    pos, used_h = pack(items, 512)
    AH = pow2(used_h + 1)
    atlas = Image.new("RGBA", (512, AH), (255, 255, 255, 0))
    for n, im, lw, lh in shapes:
        x, y = pos[n]
        atlas.paste(im, (x, y))
        lua.append("S.%s = { %d, %d, %d, %d, %d, %d }" % (n, x, y, im.size[0], im.size[1], lw, lh))
    atlas.save(os.path.join(OUT, "guis/textures/ppu/shapes%s.png" % suffix))
    print("shapes%s.png 512x%d" % (suffix, AH))


for SCALE, suffix in SETS:
    build_set(SCALE, suffix)
lua.append("PPU_ASSETS.shadow_margin = 48")
lua.append("PPU_ASSETS.shadow_slice = 96")

with open(os.path.join(OUT, "ppu_assets.lua"), "w", newline="\n") as f:
    f.write("\n".join(lua) + "\n")
print("lua bytes", os.path.getsize(os.path.join(OUT, "ppu_assets.lua")))
